FROM busybox
MAINTAINER Pascal Andy

#                         @@@ VALUE @@@
ENV PATH_CLIENT_ID "/var/www/99999101AD/ghost/content"

# Create default ghost content dirs
RUN mkdir -p $PATH_CLIENT_ID/apps
RUN mkdir -p $PATH_CLIENT_ID/images
RUN mkdir -p $PATH_CLIENT_ID/themes
RUN mkdir -p $PATH_CLIENT_ID/data
