FROM busybox
MAINTAINER Pascal Andy

# Create default ghost content dirs
RUN mkdir -p /var/www/99999101AC/ghost/content/apps
RUN mkdir -p /var/www/99999101AC/ghost/content/images
RUN mkdir -p /var/www/99999101AC/ghost/content/themes
RUN mkdir -p /var/www/99999101AC/ghost/content/data