data:
  build: ./data
  volumes:
    - /var/lib/mysql
    - /var/www/99999101AC/ghost/content
#    - /Users/mewm/www/ghost-theme:/var/www/ghost/content/themes/casper This can be added for theme development. Comment out the theme stuff in run-ghost.sh before rebuilding
  restart: always
db:
  build: ./mariadb
  ports:
    - "3305:3305"
  volumes_from:
    - data
  environment:
    - DEFAULT_USER=99999101AC # A user with this name will be created
    - DEFAULT_PASS=BWiaMCx2tpELAP34T99999101AAz
    - PORT=3305
  restart: always
web:
  build: ./ghost
  ports:
    - "10001:2368"
  links:
    - db:database
  volumes_from:
    - data
  environment:
    - DB_HOST=database
    - DB_CLIENT=mysql
    - DB_USER=99999101AC
    - DB_PASSWORD=BWiaMCx2tpELAP34T99999101AAz
    - DB_PORT=3305
    - DB_DATABASE=ghost
    - NODE_ENV=production
    - URL=http://dockercluster.tk
    - VIRTUAL_HOST=dockercluster.tk
    - THEME_SOURCE=https://github.com/mewm/ghost-theme # Git repo to fetch theme from
    - NEW_RELIC_LICENSE_KEY=<api key here>
  restart: always
newrelicservermon:
  image: uzyexe/newrelic
  hostname: charmander.mewm.org
  environment:
    - NEW_RELIC_LICENSE_KEY=<api key here>
  restart: always
